name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2ce0071f62426d476646f18383d50201d48cf8ea9017603051de8de7225a3e4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"
