name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c61915718ea2296b3009dcdb5194c044556ddf6fa722ab8724cef93573f0ac"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
