name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc51217f62583b87537255826f112be360d9a00b2d3b22516f8b2ff29520cc2e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"
