name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a027fdb130baab89e280c5307a3002c124a5d0aae66ac70f0e0dc0ac53b493b9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"
