name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4db059709a688b653dfa7077aee685f61fc72ca8f63809003acdb870e40382d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
