name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ca4efaf946df6eec79da3f9198c5558b927c19076618422980d2c3304df1ab5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"
