name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36b9db4aa0327d33bf272dd094a45006e4bbc27dde4f9bdb4201a8e983e7168a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"
