name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f636e3c3497d360cb763c7a0d676ae94536c507225765ee511b6dd331f42cbb5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
