name = "Cobblemon Balignonniere"
author = "Gudf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b82322a205b6c0217c740b7ee64af7560d9cd53025ed2b735f391d7f2266c89"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"
