[flavor_groups.minimap]
name = "Carte"
description = "Quel mod voulez-vous utiliser pour la carte?"
side = "client"
[[flavor_groups.minimap.choices]]
id = "none"
name = "Aucun"
description = "Ne pas installer de mod de carte."
[[flavor_groups.minimap.choices]]
id = "xaero"
name = "Xaero"
description = "Utiliser Xaero's Minimap et Xaero's Worldmap."
[[flavor_groups.minimap.choices]]
id = "journeymap"
name = "JourneyMap"
description = "Utiliser JourneyMap."
[[flavor_groups.minimap.choices]]
id = "hoofprint"
name = "Hoofprint"
description = "Utiliser Hoofprint. Pas de minimap, ne montrera pas les icônes de pokémon."

[metafile.xaeros-minimap]
flavors = "xaero"
[metafile.xaeros-world-map]
flavors = "xaero"
[metafile.hoofprint]
flavors = "hoofprint"
[metafile.journeymap]
flavors = "journeymap"
[metafile.journeymap-integration]
flavors = "journeymap"
[metafile.journey-pac]
flavors = "journeymap"


[flavor_groups.distant_horizons]
name = "Distant Horizon"
description = "Voulez-vous installer Distant Horizons pour des distances d'affichages très élevées ? (/!\\ Très gourmand!)"
side = "client"
[[flavor_groups.distant_horizons.choices]]
id = "dh"
name = "Oui"
description = "Installer Distant Horizons"
[[flavor_groups.distant_horizons.choices]]
id = "nodh"
name = "None"
description = "Ne pas installer Distant Horizons"

[metafile.distanthorizons]
flavors = "dh"
