# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

[adaptive_ticking]
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true

[light_sources.settings.entities.minecraft]
	glow_item_frame = false

[light_sources.settings.entities.cobblemon]
	empty_pokeball = true
	npc = true
	pokemon = true
	generic_bedrock = true
	chest_boat = true
	poke_bobber = true
	boat = true

[light_sources.settings.entities.rad-gyms]
	gym_trainer = true
